server:
  port: 8999

spring:
  datasource:
    url: jdbc:mysql://39.106.38.77:3306/yaouguoji?useSSL=false
    username: yaouguoji
    password: liuwen
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.bester.nebulasinfo.entity
logging:
  level:
    com:
      bester:
        nebulasinfo: DEBUG